'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Manga

    '''<summary>
    '''cph_head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cph_head As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''frm_master control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frm_master As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''cph_cari control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cph_cari As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''tbx_cari control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_cari As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbl_menu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_menu As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''tr_show control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_show As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''tr_hide1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_hide1 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''mn_admin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mn_admin As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''tr_hide2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_hide2 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''tr_hide3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_hide3 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''tr_hide5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_hide5 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''mn_tarif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mn_tarif As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''tr_hide4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_hide4 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''tr_hide6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_hide6 As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''btn_logout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_logout As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btn_login control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_login As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cph_slide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cph_slide As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''cph_tombol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cph_tombol As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''cph_judul control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cph_judul As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''cph_isi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cph_isi As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
