'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DetailVolume

    '''<summary>
    '''btn_kembali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_kembali As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_sunting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_sunting As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_simpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_simpan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_nama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_nama As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbl_tambah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_tambah As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lbl_kd_volume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_kd_volume As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbx_judul control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_judul As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbx_volume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_volume As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbx_jumlah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_jumlah As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbx_stok control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_stok As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''created_by control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents created_by As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''tbx_created_by control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_created_by As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''created_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents created_date As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''tbx_created_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_created_date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''modified_by control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modified_by As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''tbx_modified_by control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_modified_by As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''modified_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modified_date As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''tbx_modified_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_modified_date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_hapus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_hapus As Global.System.Web.UI.WebControls.Button
End Class
