'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TambahPeminjaman

    '''<summary>
    '''btn_kembali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_kembali As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_proses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_proses As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbl_tambah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_tambah As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''tbx_kd_anggota control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_kd_anggota As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddl_hari control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_hari As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbx_volume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_volume As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbx_jumlah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_jumlah As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_tambah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_tambah As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gdv_tampil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdv_tampil As Global.System.Web.UI.WebControls.GridView
End Class
