'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TambahBuku

    '''<summary>
    '''btn_kembali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_kembali As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_simpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_simpan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbl_tambah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_tambah As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''fup_gambar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fup_gambar As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''tbx_nama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_nama As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbx_tahun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_tahun As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbx_pengarang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_pengarang As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbx_penulis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_penulis As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cbl_kategori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbl_kategori As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''tbx_sinopsis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_sinopsis As Global.System.Web.UI.WebControls.TextBox
End Class
