'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TambahVolume

    '''<summary>
    '''btn_kembali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_kembali As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_simpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_simpan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbl_tambah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_tambah As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''tbx_judul control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_judul As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbx_volume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_volume As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbx_jumlah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbx_jumlah As Global.System.Web.UI.WebControls.TextBox
End Class
