'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Detailmanga

    '''<summary>
    '''btn_kembali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_kembali As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_nama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_nama As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbl_detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_detail As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''Img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Img As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''strNama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents strNama As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''strTahun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents strTahun As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''strPengarang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents strPengarang As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''strPenulis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents strPenulis As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''strKategori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents strKategori As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''bul_kategori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bul_kategori As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''strSinopsis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents strSinopsis As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''gdv_tampil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdv_tampil As Global.System.Web.UI.WebControls.GridView
End Class
